name: check-staging

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-staging:
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 90
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: '4.5'} # Update R version every dependency freeze.
          - {os: windows-latest, r: '4.5'}
          - {os: ubuntu-latest, r: '4.5', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: true
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false

    steps:
      - name: Check out package.
        uses: actions/checkout@v5

      - name: Set up pandoc.
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R.
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          cran: https://packagemanager.posit.co/cran/2025-07-15
          extra-repositories: https://staging.r-multiverse.org

      - name: Install dependencies.
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check package.
        uses: r-lib/actions/check-r-package@v2
